-- MySQL Script generated by MySQL Workbench
-- vie 07 dic 2018 08:17:07 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `dni_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `tipo_usuario` INT NOT NULL DEFAULT 0,
  `estado_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`tipo_ropa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`tipo_ropa` (
  `id_tipo_ropa` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_ropa` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_ropa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`sub_tipo_ropa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`sub_tipo_ropa` (
  `id_sub_tipo_ropa` INT NOT NULL AUTO_INCREMENT,
  `nombre_sub_tipo_ropa` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_sub_tipo_ropa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`ropa_tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ropa_tienda` (
  `id_ropa_tienda` INT NOT NULL AUTO_INCREMENT,
  `titulo_ropa` VARCHAR(50) NOT NULL,
  `color_ropa` VARCHAR(45) NOT NULL,
  `descripcion_ropa` LONGTEXT NOT NULL,
  `tipo_ropa` INT NOT NULL,
  `sub_tipo_ropa` INT NOT NULL,
  `imagen_ropa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_ropa_tienda`),
  INDEX `fk_ropa_tienda_tipo_ropa_idx` (`tipo_ropa` ASC),
  INDEX `fk_ropa_tienda_sub_tipo_ropa_idx` (`sub_tipo_ropa` ASC),
  CONSTRAINT `fk_ropa_tienda_tipo_ropa`
    FOREIGN KEY (`tipo_ropa`)
    REFERENCES `ecommerce`.`tipo_ropa` (`id_tipo_ropa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ropa_tienda_sub_tipo_ropa`
    FOREIGN KEY (`sub_tipo_ropa`)
    REFERENCES `ecommerce`.`sub_tipo_ropa` (`id_sub_tipo_ropa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`carrito_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`carrito_compra` (
  `id_carrito_compra` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `precio_articulo` DECIMAL(10,4) NOT NULL,
  `cantidad_articulo` INT NOT NULL,
  PRIMARY KEY (`id_carrito_compra`),
  INDEX `fk_carrito_compra_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_carrito_compra_ropa_tienda_idx` (`id_articulo` ASC),
  CONSTRAINT `fk_carrito_compra_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecommerce`.`usuarios` (`id_usuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carrito_compra_ropa_tienda`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `ecommerce`.`ropa_tienda` (`id_ropa_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`listado_tipos_subtipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`listado_tipos_subtipos` (
  `id_listado_tipos_subtipos` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_ropa` INT NOT NULL,
  `id_sub_tipo_ropa` INT NOT NULL,
  PRIMARY KEY (`id_listado_tipos_subtipos`),
  INDEX `fk_listado_tipos_subtipos_tipo_ropa_idx` (`id_tipo_ropa` ASC),
  INDEX `fk_listado_tipos_subtipos_sub_tipo_ropa_idx` (`id_sub_tipo_ropa` ASC),
  CONSTRAINT `fk_listado_tipos_subtipos_tipo_ropa`
    FOREIGN KEY (`id_tipo_ropa`)
    REFERENCES `ecommerce`.`tipo_ropa` (`id_tipo_ropa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_listado_tipos_subtipos_sub_tipo_ropa`
    FOREIGN KEY (`id_sub_tipo_ropa`)
    REFERENCES `ecommerce`.`sub_tipo_ropa` (`id_sub_tipo_ropa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad_articulo` INT NOT NULL DEFAULT 1,
  `total_compra` DECIMAL(10,4) NOT NULL,
  `metodo_de_pago` VARCHAR(45) NOT NULL,
  `estado_compra` INT NOT NULL,
  `numero_referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_compras`),
  INDEX `fk_compras_usuarios_idx` (`id_usuario` ASC),
  INDEX `fk_compras_articulo_idx` (`id_articulo` ASC),
  CONSTRAINT `fk_compras_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecommerce`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_articulo`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `ecommerce`.`ropa_tienda` (`id_ropa_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
